### ISSUE TITLE
PDF contains broken links

### ISSUE THREAD

**Issue by RHodzelmans** [ro14nd-talks/kubernetes-patterns#1]
https://github.com/ro14nd-talks/kubernetes-patterns/blob/master/kubernetes-patterns.pdf contains 404's like this one:

ERROR: The attempt to fetch slides/kubernetes/overview.html failed
with the HTTP status 404. Check your browser's JavaScript console for
more details.

**Comment by rhuss** [comment]
Thanks for the heads up ! Should be fixed now ...
